version: '3.8'

services:
  frontend:
    build: ./itwords_display
    container_name: itwords-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_ssl.conf:/etc/nginx/nginx.conf:ro
      - /home/ec2-user/ssl/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /home/ec2-user/ssl/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - itwords-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./itwords_api
    container_name: itwords-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mysql_itwordslearning?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=xcx981211
    networks:
      - itwords-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: itwords-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xcx981211
      - MYSQL_DATABASE=mysql_itwordslearning
      - MYSQL_USER=itwords_user
      - MYSQL_PASSWORD=itwords_password
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - itwords-images_mysql_data:/var/lib/mysql
    networks:
      - itwords-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  itwords-images_mysql_data:
    external: true

networks:
  itwords-network:
    driver: bridge
